name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - name: Enable Flutter web
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter packages get

      - name: Build web app
        run: flutter build web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_WEB }}
          publish_dir: ./build/web
          publish_branch: gh-pages
          publish_dir: ./build/web
          destination_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_WEB }} 