[build]
  base = "portfoliov2"                     # <-- importante: le dices dónde está tu código
  command = "flutter build web"
  publish = "portfoliov2/build/web"        # <-- ajustado al nuevo contexto

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
