name: portfoliov2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  easy_localization: ^3.0.7+1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  font_awesome_flutter: ^10.8.0
  get: ^4.7.2
  provider: ^6.1.5
  theme_provider: ^0.6.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/translations/
    - assets/translations/es.json
    - assets/translations/en.json
    - assets/data/
    - assets/img/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/img/me.png"
  web:
    generate: true
    image_path: "assets/img/me.png"
    