name: Flutter Web

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - name: Enable Flutter web
        run: flutter config --enable-web
        working-directory: portfoliov2

      - name: Install dependencies
        run: flutter pub get
        working-directory: portfoliov2

      - name: Build web app
        run: flutter build web
        working-directory: portfoliov2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_WEB }}
          publish_dir: ./portfoliov2/build/web
